# Generated by Django 4.2.4 on 2024-03-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_mechanicprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqtomechanic',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending')], default='pending', max_length=200),
        ),
    ]
