# Generated by Django 4.2.4 on 2024-03-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_reqtomechanic_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending')], default='pending', max_length=200),
        ),
    ]
