# Generated by Django 4.2.4 on 2024-03-21 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_req', to='app.reqtomechanic'),
        ),
    ]
