# Generated by Django 4.2.4 on 2024-03-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_feedback_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcar',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available')], default='pending', max_length=200),
        ),
    ]
