# Generated by Django 4.2.4 on 2024-03-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rentcar_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreserve',
            name='ticket_code',
        ),
        migrations.AlterField(
            model_name='rentcar',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available')], default='available', max_length=200),
        ),
    ]
