# Generated by Django 5.0.2 on 2024-04-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/images/profile/default.jpg', null=True, upload_to='mech_pics'),
        ),
    ]
