# Generated by Django 5.0.1 on 2024-06-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_mechanicprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicprofile',
            name='specialized_in',
            field=models.CharField(choices=[('Two Wheeler', 'Two Wheeler'), ('Four Wheeler', 'Four Wheeler'), ('Heavy Vehicle', 'Heavy Vehicle')], max_length=200),
        ),
    ]
