# Generated by Django 5.0.1 on 2024-06-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_mechanicprofile_specialized_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicprofile',
            name='specialized_in',
            field=models.CharField(choices=[('two_wheeler', 'Two Wheeler'), ('four_wheeler', 'Four Wheeler'), ('heavy_vehicle', 'Heavy Vehicle')], max_length=200),
        ),
    ]
