# Generated by Django 5.0.1 on 2024-06-26 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_mechanicprofile_specialized_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acholdername', models.CharField(max_length=100)),
                ('accno', models.PositiveBigIntegerField()),
                ('cvv', models.IntegerField()),
                ('exp', models.DateField()),
                ('amount', models.PositiveBigIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mechanicprofile')),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reqtomechanic')),
            ],
        ),
    ]
