# Generated by Django 5.0.1 on 2024-06-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_userpayment_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqtomechanic',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
