# Generated by Django 5.0.1 on 2024-06-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_reqtomechanic_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqtomechanic',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('Payment Pending', 'Payment Pending'), ('pending', 'Pending')], default='pending', max_length=200),
        ),
    ]
